### ISSUE TITLE
Possible duplicate def in GDT header?

### ISSUE THREAD

**Issue by 343GuiltySpark-04** [343GuiltySpark-04/VoyagerOS64#5]
GCC said that the GDT struct had a duplicate def so i removed the supposed duplicate in commit `be2101b2cc655e6831aa153373204bed6ba047f3` 
@LittleCodingFox

**Comment by LittleCodingFox** [comment]
Doesn't look like a problem for me, maybe I mistyped. Looks Good To Me! (LGTM)

**Comment by 343GuiltySpark-04** [comment]
yeah It works fine without the supposed duplicate so i'm gonna leave the fix.
